export const FETCH_RECIPIENTS_REQUESTED = 'FETCH_RECIPIENTS_REQUESTED';
export const FETCH_RECIPIENTS_SUCCEEDED = 'FETCH_RECIPIENTS_SUCCEEDED';

export const ADD_RECIPIENT_REQUESTED = 'ADD_RECIPIENT_REQUESTED';
export const ADD_RECIPIENT_SUCCEEDED = 'ADD_RECIPIENT_SUCCEEDED';

export const UPDATE_RECIPIENT_REQUESTED = 'UPDATE_RECIPIENT_REQUESTED';
export const UPDATE_RECIPIENT_SUCCEEDED = 'UPDATE_RECIPIENT_SUCCEEDED';

export const DELETE_RECIPIENTS_REQUESTED = 'DELETE_RECIPIENTS_REQUESTED';
export const DELETE_RECIPIENTS_SUCCEEDED = 'DELETE_RECIPIENTS_SUCCEEDED';

export const SELECTED_RECIPIENTS_CHANGED = 'SELECTED_RECIPIENTS_CHANGED';
